### ISSUE TITLE
Missing icon in search results under Gnome 42.1

### ISSUE THREAD

**Issue by linuxundich** [alexmurray/remmina-search-provider#35]
Running Remmina Search Provide 14 under Gnome 42.1 with the standard theme and standard icons under Arch Linux. When I search for a remote connection, there's an icon missing (please take a look at the screenshot).

![remmina-search-provider](https://user-images.githubusercontent.com/1716643/171152075-d8dfb367-ab78-4fea-92ad-86612b06ff38.png)

**Comment by alexmurray** [comment]
Thanks for reporting this issue - actually this looks to be a result of a change to the icon names used by upstream remmina - https://gitlab.com/Remmina/Remmina/-/commit/c29c192c7b8bda7d4292436f7d74b79a905b188f

**Comment by alexmurray** [comment]
Should be fixed with https://github.com/alexmurray/remmina-search-provider/commit/1ca3bd03a7bb108486a36b64bc4d39064dbbd9a5 - if you are able to test this that would be great, but I will likely package and upload a new version of the extension to extensions.gnome.org in the next few days regardless. Thanks.
